import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * One flat config for the whole workspace. Each package's `lint` script runs
 * `eslint .` and ESLint walks up to find this file, so Turbo can fan the task
 * out per package while the rules stay in one place.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.output/**",
      "**/.nitro/**",
      "**/.turbo/**",
      "**/.tanstack/**",
      // generated by the TanStack router plugin
      "**/routeTree.gen.ts",
      // generated by drizzle-kit
      "packages/db/drizzle/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
    },
    rules: {
      // The codebase leans on `any` in places the PRD schedules for later
      // work (W2's packages/core extraction, W3's typed clients). Warn so the
      // count is visible without failing the pipeline on pre-existing debt.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],

      // W4: Hugeicons is the icon library, reached through one wrapper. These
      // are the rules that keep the migration from drifting back.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "lucide-react",
              message:
                "Use @hugeicons/core-free-icons with <Icon> from @formdrop/ui instead — see the PRD, W4.",
            },
            {
              // Section 4.7 asks for size and colour defaults in a single
              // place. They only stay there if reaching past the wrapper is
              // an error rather than a habit -- packages/ui is exempt below,
              // since that is where the wrapper renders.
              name: "@hugeicons/react",
              message:
                "Import <Icon> from @formdrop/ui rather than HugeiconsIcon directly — it owns the size default (PRD W4.7).",
            },
          ],
        },
      ],
    },
  },

  // W4 acceptance: "Zero raw hex values outside packages/ui tokens." Getting
  // there took a sweep of 68 of them; this is what stops the 69th. A colour
  // belongs in tokens.css, applied as a class -- and where a class genuinely
  // cannot reach (Recharts props, email inline styles, an SVG logo's fill),
  // packages/ui exports the values as `palette` and `brand`.
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value=/^#[0-9a-fA-F]{3}([0-9a-fA-F]{3}([0-9a-fA-F]{2})?)?$/]",
          message:
            "Raw hex colour. Use a token class, or import { palette } / { brand } from @formdrop/ui where a class cannot reach (PRD W4 acceptance).",
        },
      ],
    },
  },

  // The wrapper itself. Somewhere has to import HugeiconsIcon, and this is
  // the one file allowed to -- that is the whole point of the rule above.
  {
    files: ["packages/ui/src/icon.tsx"],
    rules: {
      "no-restricted-imports": "off",
    },
  },

  // Node scripts and config files
  {
    files: [
      "**/*.config.{js,ts}",
      // .mjs as well: the SDK's size budget check is one, and a build script
      // that cannot call console.log is not much of a build script.
      "**/scripts/**/*.{ts,mjs}",
      "packages/db/**/*.ts",
      "apps/api/**/*.ts",
    ],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
      },
    },
    rules: {
      "no-console": "off",
    },
  },
);
