import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * One flat config for the whole workspace. Each package's `lint` script runs
 * `eslint .` and ESLint walks up to find this file, so Turbo can fan the task
 * out per package while the rules stay in one place.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.output/**",
      "**/.nitro/**",
      "**/.turbo/**",
      "**/.tanstack/**",
      // generated by the TanStack router plugin
      "**/routeTree.gen.ts",
      // generated by drizzle-kit
      "packages/db/drizzle/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
    },
    rules: {
      // The codebase leans on `any` in places the PRD schedules for later
      // work (W2's packages/core extraction, W3's typed clients). Warn so the
      // count is visible without failing the pipeline on pre-existing debt.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],

      // W4: Hugeicons is the icon library. This is the rule that keeps the
      // migration from drifting back.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "lucide-react",
              message:
                "Use @hugeicons/core-free-icons with HugeiconsIcon instead — see the PRD, W4.",
            },
          ],
        },
      ],
    },
  },

  // Node scripts and config files
  {
    files: [
      "**/*.config.{js,ts}",
      "**/scripts/**/*.ts",
      "packages/db/**/*.ts",
      "apps/api/**/*.ts",
    ],
    rules: {
      "no-console": "off",
    },
  },
);
