/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as IngestSplatRouteImport } from './routes/ingest/$'
import { Route as DocsIntegrationsRouteImport } from './routes/docs/integrations'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsFormsRouteImport } from './routes/docs/forms'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as ApiVerifyRecipientRouteImport } from './routes/api/verify-recipient'
import { Route as ApiSubscriptionRouteImport } from './routes/api/subscription'
import { Route as ApiFormsRouteImport } from './routes/api/forms'
import { Route as ApiApiKeysRouteImport } from './routes/api/api-keys'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as marketingWelcomeToProRouteImport } from './routes/(marketing)/welcome-to-pro'
import { Route as marketingVerifyRecipientRouteImport } from './routes/(marketing)/verify-recipient'
import { Route as marketingVerifyEmailRouteImport } from './routes/(marketing)/verify-email'
import { Route as marketingSignupRouteImport } from './routes/(marketing)/signup'
import { Route as marketingPrivacyRouteImport } from './routes/(marketing)/privacy'
import { Route as marketingPricingRouteImport } from './routes/(marketing)/pricing'
import { Route as marketingLoginRouteImport } from './routes/(marketing)/login'
import { Route as appAppRouteImport } from './routes/(app)/app'
import { Route as adminAdminRouteImport } from './routes/(admin)/admin'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as ApiUserSettingsRouteImport } from './routes/api/user/settings'
import { Route as ApiFormsFormIdRouteImport } from './routes/api/forms/$formId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminFormsRouteImport } from './routes/api/admin/forms'
import { Route as appAppSettingsRouteImport } from './routes/(app)/app/settings'
import { Route as appAppApiKeysRouteImport } from './routes/(app)/app/api-keys'
import { Route as appAppAnalyticsRouteImport } from './routes/(app)/app/analytics'
import { Route as adminAdminSubmissionsRouteImport } from './routes/(admin)/admin/submissions'
import { Route as adminAdminSettingsRouteImport } from './routes/(admin)/admin/settings'
import { Route as adminAdminFormsRouteImport } from './routes/(admin)/admin/forms'
import { Route as appAppFormsIndexRouteImport } from './routes/(app)/app/forms/index'
import { Route as adminAdminUsersIndexRouteImport } from './routes/(admin)/admin/users/index'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack/callback'
import { Route as ApiIntegrationsSlackAuthorizeRouteImport } from './routes/api/integrations/slack/authorize'
import { Route as ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport } from './routes/api/integrations/google-sheets/spreadsheets'
import { Route as ApiIntegrationsGoogleSheetsDisconnectRouteImport } from './routes/api/integrations/google-sheets/disconnect'
import { Route as ApiIntegrationsGoogleSheetsConfigureRouteImport } from './routes/api/integrations/google-sheets/configure'
import { Route as ApiIntegrationsGoogleSheetsCallbackRouteImport } from './routes/api/integrations/google-sheets/callback'
import { Route as ApiIntegrationsGoogleSheetsAuthorizeRouteImport } from './routes/api/integrations/google-sheets/authorize'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord/callback'
import { Route as ApiIntegrationsDiscordAuthorizeRouteImport } from './routes/api/integrations/discord/authorize'
import { Route as ApiFormsFormIdSubmissionsRouteImport } from './routes/api/forms/$formId/submissions'
import { Route as ApiFormsFormIdRecipientsRouteImport } from './routes/api/forms/$formId/recipients'
import { Route as ApiFormsFormIdExportRouteImport } from './routes/api/forms/$formId/export'
import { Route as ApiFormsFormIdDisconnectSlackRouteImport } from './routes/api/forms/$formId/disconnect-slack'
import { Route as ApiFormsFormIdDisconnectDiscordRouteImport } from './routes/api/forms/$formId/disconnect-discord'
import { Route as ApiFormsFormIdAnalyticsRouteImport } from './routes/api/forms/$formId/analytics'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'
import { Route as ApiAdminSettingsClearOldSubmissionsRouteImport } from './routes/api/admin/settings/clear-old-submissions'
import { Route as ApiAdminFormsFormIdRouteImport } from './routes/api/admin/forms/$formId'
import { Route as appAppFormsIdRouteImport } from './routes/(app)/app/forms/$id'
import { Route as adminAdminUsersUserIdRouteImport } from './routes/(admin)/admin/users/$userId'
import { Route as ApiFormsFormIdSubmissionsSubmissionIdRouteImport } from './routes/api/forms/$formId/submissions/$submissionId'
import { Route as ApiFormsFormIdRecipientsRecipientIdRouteImport } from './routes/api/forms/$formId/recipients/$recipientId'
import { Route as appAppFormsIdSubmissionsRouteImport } from './routes/(app)/app/forms/$id/submissions'
import { Route as appAppFormsIdSettingsRouteImport } from './routes/(app)/app/forms/$id/settings'
import { Route as appAppFormsIdNotificationsRouteImport } from './routes/(app)/app/forms/$id/notifications'
import { Route as appAppFormsIdIntegrationsRouteImport } from './routes/(app)/app/forms/$id/integrations'
import { Route as appAppFormsIdAnalyticsRouteImport } from './routes/(app)/app/forms/$id/analytics'
import { Route as ApiFormsFormIdRecipientsRecipientIdResendVerificationRouteImport } from './routes/api/forms/$formId/recipients/$recipientId/resend-verification'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIntegrationsRoute = DocsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormsRoute = DocsFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const ApiVerifyRecipientRoute = ApiVerifyRecipientRouteImport.update({
  id: '/api/verify-recipient',
  path: '/api/verify-recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsRoute = ApiFormsRouteImport.update({
  id: '/api/forms',
  path: '/api/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysRoute = ApiApiKeysRouteImport.update({
  id: '/api/api-keys',
  path: '/api/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingWelcomeToProRoute = marketingWelcomeToProRouteImport.update({
  id: '/(marketing)/welcome-to-pro',
  path: '/welcome-to-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingVerifyRecipientRoute =
  marketingVerifyRecipientRouteImport.update({
    id: '/(marketing)/verify-recipient',
    path: '/verify-recipient',
    getParentRoute: () => rootRouteImport,
  } as any)
const marketingVerifyEmailRoute = marketingVerifyEmailRouteImport.update({
  id: '/(marketing)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingSignupRoute = marketingSignupRouteImport.update({
  id: '/(marketing)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingPrivacyRoute = marketingPrivacyRouteImport.update({
  id: '/(marketing)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingPricingRoute = marketingPricingRouteImport.update({
  id: '/(marketing)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingLoginRoute = marketingLoginRouteImport.update({
  id: '/(marketing)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: '/(app)/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRoute = adminAdminRouteImport.update({
  id: '/(admin)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminRoute,
} as any)
const ApiUserSettingsRoute = ApiUserSettingsRouteImport.update({
  id: '/api/user/settings',
  path: '/api/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsFormIdRoute = ApiFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => ApiFormsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFormsRoute = ApiAdminFormsRouteImport.update({
  id: '/api/admin/forms',
  path: '/api/admin/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppSettingsRoute = appAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appAppRoute,
} as any)
const appAppApiKeysRoute = appAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => appAppRoute,
} as any)
const appAppAnalyticsRoute = appAppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appAppRoute,
} as any)
const adminAdminSubmissionsRoute = adminAdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminSettingsRoute = adminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminFormsRoute = adminAdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => adminAdminRoute,
} as any)
const appAppFormsIndexRoute = appAppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => appAppRoute,
} as any)
const adminAdminUsersIndexRoute = adminAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => adminAdminRoute,
} as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackAuthorizeRoute =
  ApiIntegrationsSlackAuthorizeRouteImport.update({
    id: '/api/integrations/slack/authorize',
    path: '/api/integrations/slack/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsSpreadsheetsRoute =
  ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport.update({
    id: '/api/integrations/google-sheets/spreadsheets',
    path: '/api/integrations/google-sheets/spreadsheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsDisconnectRoute =
  ApiIntegrationsGoogleSheetsDisconnectRouteImport.update({
    id: '/api/integrations/google-sheets/disconnect',
    path: '/api/integrations/google-sheets/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsConfigureRoute =
  ApiIntegrationsGoogleSheetsConfigureRouteImport.update({
    id: '/api/integrations/google-sheets/configure',
    path: '/api/integrations/google-sheets/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsCallbackRoute =
  ApiIntegrationsGoogleSheetsCallbackRouteImport.update({
    id: '/api/integrations/google-sheets/callback',
    path: '/api/integrations/google-sheets/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsAuthorizeRoute =
  ApiIntegrationsGoogleSheetsAuthorizeRouteImport.update({
    id: '/api/integrations/google-sheets/authorize',
    path: '/api/integrations/google-sheets/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordAuthorizeRoute =
  ApiIntegrationsDiscordAuthorizeRouteImport.update({
    id: '/api/integrations/discord/authorize',
    path: '/api/integrations/discord/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFormsFormIdSubmissionsRoute =
  ApiFormsFormIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdRecipientsRoute =
  ApiFormsFormIdRecipientsRouteImport.update({
    id: '/recipients',
    path: '/recipients',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdExportRoute = ApiFormsFormIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiFormsFormIdRoute,
} as any)
const ApiFormsFormIdDisconnectSlackRoute =
  ApiFormsFormIdDisconnectSlackRouteImport.update({
    id: '/disconnect-slack',
    path: '/disconnect-slack',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdDisconnectDiscordRoute =
  ApiFormsFormIdDisconnectDiscordRouteImport.update({
    id: '/disconnect-discord',
    path: '/disconnect-discord',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdAnalyticsRoute = ApiFormsFormIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ApiFormsFormIdRoute,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/api/admin/users/$userId',
  path: '/api/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsClearOldSubmissionsRoute =
  ApiAdminSettingsClearOldSubmissionsRouteImport.update({
    id: '/api/admin/settings/clear-old-submissions',
    path: '/api/admin/settings/clear-old-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminFormsFormIdRoute = ApiAdminFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => ApiAdminFormsRoute,
} as any)
const appAppFormsIdRoute = appAppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => appAppRoute,
} as any)
const adminAdminUsersUserIdRoute = adminAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => adminAdminRoute,
} as any)
const ApiFormsFormIdSubmissionsSubmissionIdRoute =
  ApiFormsFormIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ApiFormsFormIdSubmissionsRoute,
  } as any)
const ApiFormsFormIdRecipientsRecipientIdRoute =
  ApiFormsFormIdRecipientsRecipientIdRouteImport.update({
    id: '/$recipientId',
    path: '/$recipientId',
    getParentRoute: () => ApiFormsFormIdRecipientsRoute,
  } as any)
const appAppFormsIdSubmissionsRoute =
  appAppFormsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => appAppFormsIdRoute,
  } as any)
const appAppFormsIdSettingsRoute = appAppFormsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appAppFormsIdRoute,
} as any)
const appAppFormsIdNotificationsRoute =
  appAppFormsIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => appAppFormsIdRoute,
  } as any)
const appAppFormsIdIntegrationsRoute =
  appAppFormsIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => appAppFormsIdRoute,
  } as any)
const appAppFormsIdAnalyticsRoute = appAppFormsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appAppFormsIdRoute,
} as any)
const ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute =
  ApiFormsFormIdRecipientsRecipientIdResendVerificationRouteImport.update({
    id: '/resend-verification',
    path: '/resend-verification',
    getParentRoute: () => ApiFormsFormIdRecipientsRecipientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/docs': typeof DocsRouteWithChildren
  '/admin': typeof adminAdminRouteWithChildren
  '/app': typeof appAppRouteWithChildren
  '/login': typeof marketingLoginRoute
  '/pricing': typeof marketingPricingRoute
  '/privacy': typeof marketingPrivacyRoute
  '/signup': typeof marketingSignupRoute
  '/verify-email': typeof marketingVerifyEmailRoute
  '/verify-recipient': typeof marketingVerifyRecipientRoute
  '/welcome-to-pro': typeof marketingWelcomeToProRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/ingest/$': typeof IngestSplatRoute
  '/': typeof marketingIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/forms': typeof adminAdminFormsRoute
  '/admin/settings': typeof adminAdminSettingsRoute
  '/admin/submissions': typeof adminAdminSubmissionsRoute
  '/app/analytics': typeof appAppAnalyticsRoute
  '/app/api-keys': typeof appAppApiKeysRoute
  '/app/settings': typeof appAppSettingsRoute
  '/api/admin/forms': typeof ApiAdminFormsRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$formId': typeof ApiFormsFormIdRouteWithChildren
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/admin/': typeof adminAdminIndexRoute
  '/admin/users/$userId': typeof adminAdminUsersUserIdRoute
  '/app/forms/$id': typeof appAppFormsIdRouteWithChildren
  '/api/admin/forms/$formId': typeof ApiAdminFormsFormIdRoute
  '/api/admin/settings/clear-old-submissions': typeof ApiAdminSettingsClearOldSubmissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/forms/$formId/analytics': typeof ApiFormsFormIdAnalyticsRoute
  '/api/forms/$formId/disconnect-discord': typeof ApiFormsFormIdDisconnectDiscordRoute
  '/api/forms/$formId/disconnect-slack': typeof ApiFormsFormIdDisconnectSlackRoute
  '/api/forms/$formId/export': typeof ApiFormsFormIdExportRoute
  '/api/forms/$formId/recipients': typeof ApiFormsFormIdRecipientsRouteWithChildren
  '/api/forms/$formId/submissions': typeof ApiFormsFormIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/admin/users': typeof adminAdminUsersIndexRoute
  '/app/forms': typeof appAppFormsIndexRoute
  '/app/forms/$id/analytics': typeof appAppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof appAppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof appAppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof appAppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof appAppFormsIdSubmissionsRoute
  '/api/forms/$formId/recipients/$recipientId': typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
  '/api/forms/$formId/submissions/$submissionId': typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
  '/api/forms/$formId/recipients/$recipientId/resend-verification': typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRoutesByTo {
  '/app': typeof appAppRouteWithChildren
  '/login': typeof marketingLoginRoute
  '/pricing': typeof marketingPricingRoute
  '/privacy': typeof marketingPrivacyRoute
  '/signup': typeof marketingSignupRoute
  '/verify-email': typeof marketingVerifyEmailRoute
  '/verify-recipient': typeof marketingVerifyRecipientRoute
  '/welcome-to-pro': typeof marketingWelcomeToProRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/ingest/$': typeof IngestSplatRoute
  '/': typeof marketingIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/forms': typeof adminAdminFormsRoute
  '/admin/settings': typeof adminAdminSettingsRoute
  '/admin/submissions': typeof adminAdminSubmissionsRoute
  '/app/analytics': typeof appAppAnalyticsRoute
  '/app/api-keys': typeof appAppApiKeysRoute
  '/app/settings': typeof appAppSettingsRoute
  '/api/admin/forms': typeof ApiAdminFormsRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$formId': typeof ApiFormsFormIdRouteWithChildren
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/admin': typeof adminAdminIndexRoute
  '/admin/users/$userId': typeof adminAdminUsersUserIdRoute
  '/app/forms/$id': typeof appAppFormsIdRouteWithChildren
  '/api/admin/forms/$formId': typeof ApiAdminFormsFormIdRoute
  '/api/admin/settings/clear-old-submissions': typeof ApiAdminSettingsClearOldSubmissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/forms/$formId/analytics': typeof ApiFormsFormIdAnalyticsRoute
  '/api/forms/$formId/disconnect-discord': typeof ApiFormsFormIdDisconnectDiscordRoute
  '/api/forms/$formId/disconnect-slack': typeof ApiFormsFormIdDisconnectSlackRoute
  '/api/forms/$formId/export': typeof ApiFormsFormIdExportRoute
  '/api/forms/$formId/recipients': typeof ApiFormsFormIdRecipientsRouteWithChildren
  '/api/forms/$formId/submissions': typeof ApiFormsFormIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/admin/users': typeof adminAdminUsersIndexRoute
  '/app/forms': typeof appAppFormsIndexRoute
  '/app/forms/$id/analytics': typeof appAppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof appAppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof appAppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof appAppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof appAppFormsIdSubmissionsRoute
  '/api/forms/$formId/recipients/$recipientId': typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
  '/api/forms/$formId/submissions/$submissionId': typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
  '/api/forms/$formId/recipients/$recipientId/resend-verification': typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/docs': typeof DocsRouteWithChildren
  '/(admin)/admin': typeof adminAdminRouteWithChildren
  '/(app)/app': typeof appAppRouteWithChildren
  '/(marketing)/login': typeof marketingLoginRoute
  '/(marketing)/pricing': typeof marketingPricingRoute
  '/(marketing)/privacy': typeof marketingPrivacyRoute
  '/(marketing)/signup': typeof marketingSignupRoute
  '/(marketing)/verify-email': typeof marketingVerifyEmailRoute
  '/(marketing)/verify-recipient': typeof marketingVerifyRecipientRoute
  '/(marketing)/welcome-to-pro': typeof marketingWelcomeToProRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/ingest/$': typeof IngestSplatRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/(admin)/admin/forms': typeof adminAdminFormsRoute
  '/(admin)/admin/settings': typeof adminAdminSettingsRoute
  '/(admin)/admin/submissions': typeof adminAdminSubmissionsRoute
  '/(app)/app/analytics': typeof appAppAnalyticsRoute
  '/(app)/app/api-keys': typeof appAppApiKeysRoute
  '/(app)/app/settings': typeof appAppSettingsRoute
  '/api/admin/forms': typeof ApiAdminFormsRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$formId': typeof ApiFormsFormIdRouteWithChildren
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(admin)/admin/users/$userId': typeof adminAdminUsersUserIdRoute
  '/(app)/app/forms/$id': typeof appAppFormsIdRouteWithChildren
  '/api/admin/forms/$formId': typeof ApiAdminFormsFormIdRoute
  '/api/admin/settings/clear-old-submissions': typeof ApiAdminSettingsClearOldSubmissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/forms/$formId/analytics': typeof ApiFormsFormIdAnalyticsRoute
  '/api/forms/$formId/disconnect-discord': typeof ApiFormsFormIdDisconnectDiscordRoute
  '/api/forms/$formId/disconnect-slack': typeof ApiFormsFormIdDisconnectSlackRoute
  '/api/forms/$formId/export': typeof ApiFormsFormIdExportRoute
  '/api/forms/$formId/recipients': typeof ApiFormsFormIdRecipientsRouteWithChildren
  '/api/forms/$formId/submissions': typeof ApiFormsFormIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/(admin)/admin/users/': typeof adminAdminUsersIndexRoute
  '/(app)/app/forms/': typeof appAppFormsIndexRoute
  '/(app)/app/forms/$id/analytics': typeof appAppFormsIdAnalyticsRoute
  '/(app)/app/forms/$id/integrations': typeof appAppFormsIdIntegrationsRoute
  '/(app)/app/forms/$id/notifications': typeof appAppFormsIdNotificationsRoute
  '/(app)/app/forms/$id/settings': typeof appAppFormsIdSettingsRoute
  '/(app)/app/forms/$id/submissions': typeof appAppFormsIdSubmissionsRoute
  '/api/forms/$formId/recipients/$recipientId': typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
  '/api/forms/$formId/submissions/$submissionId': typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
  '/api/forms/$formId/recipients/$recipientId/resend-verification': typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/docs'
    | '/admin'
    | '/app'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/forms'
    | '/api/subscription'
    | '/api/verify-recipient'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/ingest/$'
    | '/'
    | '/docs/'
    | '/admin/forms'
    | '/admin/settings'
    | '/admin/submissions'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/api/admin/forms'
    | '/api/admin/stats'
    | '/api/admin/submissions'
    | '/api/auth/$'
    | '/api/forms/$formId'
    | '/api/user/settings'
    | '/admin/'
    | '/admin/users/$userId'
    | '/app/forms/$id'
    | '/api/admin/forms/$formId'
    | '/api/admin/settings/clear-old-submissions'
    | '/api/admin/users/$userId'
    | '/api/forms/$formId/analytics'
    | '/api/forms/$formId/disconnect-discord'
    | '/api/forms/$formId/disconnect-slack'
    | '/api/forms/$formId/export'
    | '/api/forms/$formId/recipients'
    | '/api/forms/$formId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/admin/users'
    | '/app/forms'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/forms/$formId/recipients/$recipientId'
    | '/api/forms/$formId/submissions/$submissionId'
    | '/api/forms/$formId/recipients/$recipientId/resend-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/forms'
    | '/api/subscription'
    | '/api/verify-recipient'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/ingest/$'
    | '/'
    | '/docs'
    | '/admin/forms'
    | '/admin/settings'
    | '/admin/submissions'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/api/admin/forms'
    | '/api/admin/stats'
    | '/api/admin/submissions'
    | '/api/auth/$'
    | '/api/forms/$formId'
    | '/api/user/settings'
    | '/admin'
    | '/admin/users/$userId'
    | '/app/forms/$id'
    | '/api/admin/forms/$formId'
    | '/api/admin/settings/clear-old-submissions'
    | '/api/admin/users/$userId'
    | '/api/forms/$formId/analytics'
    | '/api/forms/$formId/disconnect-discord'
    | '/api/forms/$formId/disconnect-slack'
    | '/api/forms/$formId/export'
    | '/api/forms/$formId/recipients'
    | '/api/forms/$formId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/admin/users'
    | '/app/forms'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/forms/$formId/recipients/$recipientId'
    | '/api/forms/$formId/submissions/$submissionId'
    | '/api/forms/$formId/recipients/$recipientId/resend-verification'
  id:
    | '__root__'
    | '/docs'
    | '/(admin)/admin'
    | '/(app)/app'
    | '/(marketing)/login'
    | '/(marketing)/pricing'
    | '/(marketing)/privacy'
    | '/(marketing)/signup'
    | '/(marketing)/verify-email'
    | '/(marketing)/verify-recipient'
    | '/(marketing)/welcome-to-pro'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/forms'
    | '/api/subscription'
    | '/api/verify-recipient'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/ingest/$'
    | '/(marketing)/'
    | '/docs/'
    | '/(admin)/admin/forms'
    | '/(admin)/admin/settings'
    | '/(admin)/admin/submissions'
    | '/(app)/app/analytics'
    | '/(app)/app/api-keys'
    | '/(app)/app/settings'
    | '/api/admin/forms'
    | '/api/admin/stats'
    | '/api/admin/submissions'
    | '/api/auth/$'
    | '/api/forms/$formId'
    | '/api/user/settings'
    | '/(admin)/admin/'
    | '/(admin)/admin/users/$userId'
    | '/(app)/app/forms/$id'
    | '/api/admin/forms/$formId'
    | '/api/admin/settings/clear-old-submissions'
    | '/api/admin/users/$userId'
    | '/api/forms/$formId/analytics'
    | '/api/forms/$formId/disconnect-discord'
    | '/api/forms/$formId/disconnect-slack'
    | '/api/forms/$formId/export'
    | '/api/forms/$formId/recipients'
    | '/api/forms/$formId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/(admin)/admin/users/'
    | '/(app)/app/forms/'
    | '/(app)/app/forms/$id/analytics'
    | '/(app)/app/forms/$id/integrations'
    | '/(app)/app/forms/$id/notifications'
    | '/(app)/app/forms/$id/settings'
    | '/(app)/app/forms/$id/submissions'
    | '/api/forms/$formId/recipients/$recipientId'
    | '/api/forms/$formId/submissions/$submissionId'
    | '/api/forms/$formId/recipients/$recipientId/resend-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRoute: typeof DocsRouteWithChildren
  adminAdminRoute: typeof adminAdminRouteWithChildren
  appAppRoute: typeof appAppRouteWithChildren
  marketingLoginRoute: typeof marketingLoginRoute
  marketingPricingRoute: typeof marketingPricingRoute
  marketingPrivacyRoute: typeof marketingPrivacyRoute
  marketingSignupRoute: typeof marketingSignupRoute
  marketingVerifyEmailRoute: typeof marketingVerifyEmailRoute
  marketingVerifyRecipientRoute: typeof marketingVerifyRecipientRoute
  marketingWelcomeToProRoute: typeof marketingWelcomeToProRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiApiKeysRoute: typeof ApiApiKeysRoute
  ApiFormsRoute: typeof ApiFormsRouteWithChildren
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiVerifyRecipientRoute: typeof ApiVerifyRecipientRoute
  IngestSplatRoute: typeof IngestSplatRoute
  marketingIndexRoute: typeof marketingIndexRoute
  ApiAdminFormsRoute: typeof ApiAdminFormsRouteWithChildren
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserSettingsRoute: typeof ApiUserSettingsRoute
  ApiAdminSettingsClearOldSubmissionsRoute: typeof ApiAdminSettingsClearOldSubmissionsRoute
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
  ApiIntegrationsDiscordAuthorizeRoute: typeof ApiIntegrationsDiscordAuthorizeRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsGoogleSheetsAuthorizeRoute: typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  ApiIntegrationsGoogleSheetsCallbackRoute: typeof ApiIntegrationsGoogleSheetsCallbackRoute
  ApiIntegrationsGoogleSheetsConfigureRoute: typeof ApiIntegrationsGoogleSheetsConfigureRoute
  ApiIntegrationsGoogleSheetsDisconnectRoute: typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  ApiIntegrationsGoogleSheetsSpreadsheetsRoute: typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  ApiIntegrationsSlackAuthorizeRoute: typeof ApiIntegrationsSlackAuthorizeRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/integrations': {
      id: '/docs/integrations'
      path: '/integrations'
      fullPath: '/docs/integrations'
      preLoaderRoute: typeof DocsIntegrationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/forms': {
      id: '/docs/forms'
      path: '/forms'
      fullPath: '/docs/forms'
      preLoaderRoute: typeof DocsFormsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/verify-recipient': {
      id: '/api/verify-recipient'
      path: '/api/verify-recipient'
      fullPath: '/api/verify-recipient'
      preLoaderRoute: typeof ApiVerifyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms': {
      id: '/api/forms'
      path: '/api/forms'
      fullPath: '/api/forms'
      preLoaderRoute: typeof ApiFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys': {
      id: '/api/api-keys'
      path: '/api/api-keys'
      fullPath: '/api/api-keys'
      preLoaderRoute: typeof ApiApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/welcome-to-pro': {
      id: '/(marketing)/welcome-to-pro'
      path: '/welcome-to-pro'
      fullPath: '/welcome-to-pro'
      preLoaderRoute: typeof marketingWelcomeToProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/verify-recipient': {
      id: '/(marketing)/verify-recipient'
      path: '/verify-recipient'
      fullPath: '/verify-recipient'
      preLoaderRoute: typeof marketingVerifyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/verify-email': {
      id: '/(marketing)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof marketingVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/signup': {
      id: '/(marketing)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof marketingSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/privacy': {
      id: '/(marketing)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof marketingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/pricing': {
      id: '/(marketing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/login': {
      id: '/(marketing)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof marketingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app': {
      id: '/(app)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin': {
      id: '/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/api/user/settings': {
      id: '/api/user/settings'
      path: '/api/user/settings'
      fullPath: '/api/user/settings'
      preLoaderRoute: typeof ApiUserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$formId': {
      id: '/api/forms/$formId'
      path: '/$formId'
      fullPath: '/api/forms/$formId'
      preLoaderRoute: typeof ApiFormsFormIdRouteImport
      parentRoute: typeof ApiFormsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/forms': {
      id: '/api/admin/forms'
      path: '/api/admin/forms'
      fullPath: '/api/admin/forms'
      preLoaderRoute: typeof ApiAdminFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app/settings': {
      id: '/(app)/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof appAppSettingsRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/app/api-keys': {
      id: '/(app)/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof appAppApiKeysRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/app/analytics': {
      id: '/(app)/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof appAppAnalyticsRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(admin)/admin/submissions': {
      id: '/(admin)/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof adminAdminSubmissionsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/settings': {
      id: '/(admin)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof adminAdminSettingsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/forms': {
      id: '/(admin)/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof adminAdminFormsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(app)/app/forms/': {
      id: '/(app)/app/forms/'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof appAppFormsIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(admin)/admin/users/': {
      id: '/(admin)/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminAdminUsersIndexRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/authorize': {
      id: '/api/integrations/slack/authorize'
      path: '/api/integrations/slack/authorize'
      fullPath: '/api/integrations/slack/authorize'
      preLoaderRoute: typeof ApiIntegrationsSlackAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/spreadsheets': {
      id: '/api/integrations/google-sheets/spreadsheets'
      path: '/api/integrations/google-sheets/spreadsheets'
      fullPath: '/api/integrations/google-sheets/spreadsheets'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/disconnect': {
      id: '/api/integrations/google-sheets/disconnect'
      path: '/api/integrations/google-sheets/disconnect'
      fullPath: '/api/integrations/google-sheets/disconnect'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/configure': {
      id: '/api/integrations/google-sheets/configure'
      path: '/api/integrations/google-sheets/configure'
      fullPath: '/api/integrations/google-sheets/configure'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/callback': {
      id: '/api/integrations/google-sheets/callback'
      path: '/api/integrations/google-sheets/callback'
      fullPath: '/api/integrations/google-sheets/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/authorize': {
      id: '/api/integrations/google-sheets/authorize'
      path: '/api/integrations/google-sheets/authorize'
      fullPath: '/api/integrations/google-sheets/authorize'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/authorize': {
      id: '/api/integrations/discord/authorize'
      path: '/api/integrations/discord/authorize'
      fullPath: '/api/integrations/discord/authorize'
      preLoaderRoute: typeof ApiIntegrationsDiscordAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$formId/submissions': {
      id: '/api/forms/$formId/submissions'
      path: '/submissions'
      fullPath: '/api/forms/$formId/submissions'
      preLoaderRoute: typeof ApiFormsFormIdSubmissionsRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/recipients': {
      id: '/api/forms/$formId/recipients'
      path: '/recipients'
      fullPath: '/api/forms/$formId/recipients'
      preLoaderRoute: typeof ApiFormsFormIdRecipientsRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/export': {
      id: '/api/forms/$formId/export'
      path: '/export'
      fullPath: '/api/forms/$formId/export'
      preLoaderRoute: typeof ApiFormsFormIdExportRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/disconnect-slack': {
      id: '/api/forms/$formId/disconnect-slack'
      path: '/disconnect-slack'
      fullPath: '/api/forms/$formId/disconnect-slack'
      preLoaderRoute: typeof ApiFormsFormIdDisconnectSlackRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/disconnect-discord': {
      id: '/api/forms/$formId/disconnect-discord'
      path: '/disconnect-discord'
      fullPath: '/api/forms/$formId/disconnect-discord'
      preLoaderRoute: typeof ApiFormsFormIdDisconnectDiscordRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/analytics': {
      id: '/api/forms/$formId/analytics'
      path: '/analytics'
      fullPath: '/api/forms/$formId/analytics'
      preLoaderRoute: typeof ApiFormsFormIdAnalyticsRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/api/admin/users/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings/clear-old-submissions': {
      id: '/api/admin/settings/clear-old-submissions'
      path: '/api/admin/settings/clear-old-submissions'
      fullPath: '/api/admin/settings/clear-old-submissions'
      preLoaderRoute: typeof ApiAdminSettingsClearOldSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/forms/$formId': {
      id: '/api/admin/forms/$formId'
      path: '/$formId'
      fullPath: '/api/admin/forms/$formId'
      preLoaderRoute: typeof ApiAdminFormsFormIdRouteImport
      parentRoute: typeof ApiAdminFormsRoute
    }
    '/(app)/app/forms/$id': {
      id: '/(app)/app/forms/$id'
      path: '/forms/$id'
      fullPath: '/app/forms/$id'
      preLoaderRoute: typeof appAppFormsIdRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(admin)/admin/users/$userId': {
      id: '/(admin)/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof adminAdminUsersUserIdRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/api/forms/$formId/submissions/$submissionId': {
      id: '/api/forms/$formId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/api/forms/$formId/submissions/$submissionId'
      preLoaderRoute: typeof ApiFormsFormIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ApiFormsFormIdSubmissionsRoute
    }
    '/api/forms/$formId/recipients/$recipientId': {
      id: '/api/forms/$formId/recipients/$recipientId'
      path: '/$recipientId'
      fullPath: '/api/forms/$formId/recipients/$recipientId'
      preLoaderRoute: typeof ApiFormsFormIdRecipientsRecipientIdRouteImport
      parentRoute: typeof ApiFormsFormIdRecipientsRoute
    }
    '/(app)/app/forms/$id/submissions': {
      id: '/(app)/app/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/app/forms/$id/submissions'
      preLoaderRoute: typeof appAppFormsIdSubmissionsRouteImport
      parentRoute: typeof appAppFormsIdRoute
    }
    '/(app)/app/forms/$id/settings': {
      id: '/(app)/app/forms/$id/settings'
      path: '/settings'
      fullPath: '/app/forms/$id/settings'
      preLoaderRoute: typeof appAppFormsIdSettingsRouteImport
      parentRoute: typeof appAppFormsIdRoute
    }
    '/(app)/app/forms/$id/notifications': {
      id: '/(app)/app/forms/$id/notifications'
      path: '/notifications'
      fullPath: '/app/forms/$id/notifications'
      preLoaderRoute: typeof appAppFormsIdNotificationsRouteImport
      parentRoute: typeof appAppFormsIdRoute
    }
    '/(app)/app/forms/$id/integrations': {
      id: '/(app)/app/forms/$id/integrations'
      path: '/integrations'
      fullPath: '/app/forms/$id/integrations'
      preLoaderRoute: typeof appAppFormsIdIntegrationsRouteImport
      parentRoute: typeof appAppFormsIdRoute
    }
    '/(app)/app/forms/$id/analytics': {
      id: '/(app)/app/forms/$id/analytics'
      path: '/analytics'
      fullPath: '/app/forms/$id/analytics'
      preLoaderRoute: typeof appAppFormsIdAnalyticsRouteImport
      parentRoute: typeof appAppFormsIdRoute
    }
    '/api/forms/$formId/recipients/$recipientId/resend-verification': {
      id: '/api/forms/$formId/recipients/$recipientId/resend-verification'
      path: '/resend-verification'
      fullPath: '/api/forms/$formId/recipients/$recipientId/resend-verification'
      preLoaderRoute: typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRouteImport
      parentRoute: typeof ApiFormsFormIdRecipientsRecipientIdRoute
    }
  }
}

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsFormsRoute: typeof DocsFormsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIntegrationsRoute: typeof DocsIntegrationsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsFormsRoute: DocsFormsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIntegrationsRoute: DocsIntegrationsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface adminAdminRouteChildren {
  adminAdminFormsRoute: typeof adminAdminFormsRoute
  adminAdminSettingsRoute: typeof adminAdminSettingsRoute
  adminAdminSubmissionsRoute: typeof adminAdminSubmissionsRoute
  adminAdminIndexRoute: typeof adminAdminIndexRoute
  adminAdminUsersUserIdRoute: typeof adminAdminUsersUserIdRoute
  adminAdminUsersIndexRoute: typeof adminAdminUsersIndexRoute
}

const adminAdminRouteChildren: adminAdminRouteChildren = {
  adminAdminFormsRoute: adminAdminFormsRoute,
  adminAdminSettingsRoute: adminAdminSettingsRoute,
  adminAdminSubmissionsRoute: adminAdminSubmissionsRoute,
  adminAdminIndexRoute: adminAdminIndexRoute,
  adminAdminUsersUserIdRoute: adminAdminUsersUserIdRoute,
  adminAdminUsersIndexRoute: adminAdminUsersIndexRoute,
}

const adminAdminRouteWithChildren = adminAdminRoute._addFileChildren(
  adminAdminRouteChildren,
)

interface appAppFormsIdRouteChildren {
  appAppFormsIdAnalyticsRoute: typeof appAppFormsIdAnalyticsRoute
  appAppFormsIdIntegrationsRoute: typeof appAppFormsIdIntegrationsRoute
  appAppFormsIdNotificationsRoute: typeof appAppFormsIdNotificationsRoute
  appAppFormsIdSettingsRoute: typeof appAppFormsIdSettingsRoute
  appAppFormsIdSubmissionsRoute: typeof appAppFormsIdSubmissionsRoute
}

const appAppFormsIdRouteChildren: appAppFormsIdRouteChildren = {
  appAppFormsIdAnalyticsRoute: appAppFormsIdAnalyticsRoute,
  appAppFormsIdIntegrationsRoute: appAppFormsIdIntegrationsRoute,
  appAppFormsIdNotificationsRoute: appAppFormsIdNotificationsRoute,
  appAppFormsIdSettingsRoute: appAppFormsIdSettingsRoute,
  appAppFormsIdSubmissionsRoute: appAppFormsIdSubmissionsRoute,
}

const appAppFormsIdRouteWithChildren = appAppFormsIdRoute._addFileChildren(
  appAppFormsIdRouteChildren,
)

interface appAppRouteChildren {
  appAppAnalyticsRoute: typeof appAppAnalyticsRoute
  appAppApiKeysRoute: typeof appAppApiKeysRoute
  appAppSettingsRoute: typeof appAppSettingsRoute
  appAppFormsIdRoute: typeof appAppFormsIdRouteWithChildren
  appAppFormsIndexRoute: typeof appAppFormsIndexRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppAnalyticsRoute: appAppAnalyticsRoute,
  appAppApiKeysRoute: appAppApiKeysRoute,
  appAppSettingsRoute: appAppSettingsRoute,
  appAppFormsIdRoute: appAppFormsIdRouteWithChildren,
  appAppFormsIndexRoute: appAppFormsIndexRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface ApiFormsFormIdRecipientsRecipientIdRouteChildren {
  ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute: typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}

const ApiFormsFormIdRecipientsRecipientIdRouteChildren: ApiFormsFormIdRecipientsRecipientIdRouteChildren =
  {
    ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute:
      ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute,
  }

const ApiFormsFormIdRecipientsRecipientIdRouteWithChildren =
  ApiFormsFormIdRecipientsRecipientIdRoute._addFileChildren(
    ApiFormsFormIdRecipientsRecipientIdRouteChildren,
  )

interface ApiFormsFormIdRecipientsRouteChildren {
  ApiFormsFormIdRecipientsRecipientIdRoute: typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
}

const ApiFormsFormIdRecipientsRouteChildren: ApiFormsFormIdRecipientsRouteChildren =
  {
    ApiFormsFormIdRecipientsRecipientIdRoute:
      ApiFormsFormIdRecipientsRecipientIdRouteWithChildren,
  }

const ApiFormsFormIdRecipientsRouteWithChildren =
  ApiFormsFormIdRecipientsRoute._addFileChildren(
    ApiFormsFormIdRecipientsRouteChildren,
  )

interface ApiFormsFormIdSubmissionsRouteChildren {
  ApiFormsFormIdSubmissionsSubmissionIdRoute: typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
}

const ApiFormsFormIdSubmissionsRouteChildren: ApiFormsFormIdSubmissionsRouteChildren =
  {
    ApiFormsFormIdSubmissionsSubmissionIdRoute:
      ApiFormsFormIdSubmissionsSubmissionIdRoute,
  }

const ApiFormsFormIdSubmissionsRouteWithChildren =
  ApiFormsFormIdSubmissionsRoute._addFileChildren(
    ApiFormsFormIdSubmissionsRouteChildren,
  )

interface ApiFormsFormIdRouteChildren {
  ApiFormsFormIdAnalyticsRoute: typeof ApiFormsFormIdAnalyticsRoute
  ApiFormsFormIdDisconnectDiscordRoute: typeof ApiFormsFormIdDisconnectDiscordRoute
  ApiFormsFormIdDisconnectSlackRoute: typeof ApiFormsFormIdDisconnectSlackRoute
  ApiFormsFormIdExportRoute: typeof ApiFormsFormIdExportRoute
  ApiFormsFormIdRecipientsRoute: typeof ApiFormsFormIdRecipientsRouteWithChildren
  ApiFormsFormIdSubmissionsRoute: typeof ApiFormsFormIdSubmissionsRouteWithChildren
}

const ApiFormsFormIdRouteChildren: ApiFormsFormIdRouteChildren = {
  ApiFormsFormIdAnalyticsRoute: ApiFormsFormIdAnalyticsRoute,
  ApiFormsFormIdDisconnectDiscordRoute: ApiFormsFormIdDisconnectDiscordRoute,
  ApiFormsFormIdDisconnectSlackRoute: ApiFormsFormIdDisconnectSlackRoute,
  ApiFormsFormIdExportRoute: ApiFormsFormIdExportRoute,
  ApiFormsFormIdRecipientsRoute: ApiFormsFormIdRecipientsRouteWithChildren,
  ApiFormsFormIdSubmissionsRoute: ApiFormsFormIdSubmissionsRouteWithChildren,
}

const ApiFormsFormIdRouteWithChildren = ApiFormsFormIdRoute._addFileChildren(
  ApiFormsFormIdRouteChildren,
)

interface ApiFormsRouteChildren {
  ApiFormsFormIdRoute: typeof ApiFormsFormIdRouteWithChildren
}

const ApiFormsRouteChildren: ApiFormsRouteChildren = {
  ApiFormsFormIdRoute: ApiFormsFormIdRouteWithChildren,
}

const ApiFormsRouteWithChildren = ApiFormsRoute._addFileChildren(
  ApiFormsRouteChildren,
)

interface ApiAdminFormsRouteChildren {
  ApiAdminFormsFormIdRoute: typeof ApiAdminFormsFormIdRoute
}

const ApiAdminFormsRouteChildren: ApiAdminFormsRouteChildren = {
  ApiAdminFormsFormIdRoute: ApiAdminFormsFormIdRoute,
}

const ApiAdminFormsRouteWithChildren = ApiAdminFormsRoute._addFileChildren(
  ApiAdminFormsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DocsRoute: DocsRouteWithChildren,
  adminAdminRoute: adminAdminRouteWithChildren,
  appAppRoute: appAppRouteWithChildren,
  marketingLoginRoute: marketingLoginRoute,
  marketingPricingRoute: marketingPricingRoute,
  marketingPrivacyRoute: marketingPrivacyRoute,
  marketingSignupRoute: marketingSignupRoute,
  marketingVerifyEmailRoute: marketingVerifyEmailRoute,
  marketingVerifyRecipientRoute: marketingVerifyRecipientRoute,
  marketingWelcomeToProRoute: marketingWelcomeToProRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiApiKeysRoute: ApiApiKeysRoute,
  ApiFormsRoute: ApiFormsRouteWithChildren,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiVerifyRecipientRoute: ApiVerifyRecipientRoute,
  IngestSplatRoute: IngestSplatRoute,
  marketingIndexRoute: marketingIndexRoute,
  ApiAdminFormsRoute: ApiAdminFormsRouteWithChildren,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserSettingsRoute: ApiUserSettingsRoute,
  ApiAdminSettingsClearOldSubmissionsRoute:
    ApiAdminSettingsClearOldSubmissionsRoute,
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
  ApiIntegrationsDiscordAuthorizeRoute: ApiIntegrationsDiscordAuthorizeRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsGoogleSheetsAuthorizeRoute:
    ApiIntegrationsGoogleSheetsAuthorizeRoute,
  ApiIntegrationsGoogleSheetsCallbackRoute:
    ApiIntegrationsGoogleSheetsCallbackRoute,
  ApiIntegrationsGoogleSheetsConfigureRoute:
    ApiIntegrationsGoogleSheetsConfigureRoute,
  ApiIntegrationsGoogleSheetsDisconnectRoute:
    ApiIntegrationsGoogleSheetsDisconnectRoute,
  ApiIntegrationsGoogleSheetsSpreadsheetsRoute:
    ApiIntegrationsGoogleSheetsSpreadsheetsRoute,
  ApiIntegrationsSlackAuthorizeRoute: ApiIntegrationsSlackAuthorizeRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
