/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeToProRouteImport } from './routes/welcome-to-pro'
import { Route as VerifyRecipientRouteImport } from './routes/verify-recipient'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DocsIntegrationsRouteImport } from './routes/docs/integrations'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsFormsRouteImport } from './routes/docs/forms'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as ApiVerifyRecipientRouteImport } from './routes/api/verify-recipient'
import { Route as ApiSubscriptionRouteImport } from './routes/api/subscription'
import { Route as ApiFormsRouteImport } from './routes/api/forms'
import { Route as ApiApiKeysRouteImport } from './routes/api/api-keys'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminFormsRouteImport } from './routes/admin/forms'
import { Route as AppFormsIndexRouteImport } from './routes/app/forms/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AppFormsIdRouteImport } from './routes/app/forms/$id'
import { Route as ApiUserSettingsRouteImport } from './routes/api/user/settings'
import { Route as ApiFormsFormIdRouteImport } from './routes/api/forms/$formId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminFormsRouteImport } from './routes/api/admin/forms'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AppFormsIdSubmissionsRouteImport } from './routes/app/forms/$id/submissions'
import { Route as AppFormsIdSettingsRouteImport } from './routes/app/forms/$id/settings'
import { Route as AppFormsIdNotificationsRouteImport } from './routes/app/forms/$id/notifications'
import { Route as AppFormsIdIntegrationsRouteImport } from './routes/app/forms/$id/integrations'
import { Route as AppFormsIdAnalyticsRouteImport } from './routes/app/forms/$id/analytics'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack/callback'
import { Route as ApiIntegrationsSlackAuthorizeRouteImport } from './routes/api/integrations/slack/authorize'
import { Route as ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport } from './routes/api/integrations/google-sheets/spreadsheets'
import { Route as ApiIntegrationsGoogleSheetsDisconnectRouteImport } from './routes/api/integrations/google-sheets/disconnect'
import { Route as ApiIntegrationsGoogleSheetsConfigureRouteImport } from './routes/api/integrations/google-sheets/configure'
import { Route as ApiIntegrationsGoogleSheetsCallbackRouteImport } from './routes/api/integrations/google-sheets/callback'
import { Route as ApiIntegrationsGoogleSheetsAuthorizeRouteImport } from './routes/api/integrations/google-sheets/authorize'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord/callback'
import { Route as ApiIntegrationsDiscordAuthorizeRouteImport } from './routes/api/integrations/discord/authorize'
import { Route as ApiFormsFormIdSubmissionsRouteImport } from './routes/api/forms/$formId/submissions'
import { Route as ApiFormsFormIdRecipientsRouteImport } from './routes/api/forms/$formId/recipients'
import { Route as ApiFormsFormIdExportRouteImport } from './routes/api/forms/$formId/export'
import { Route as ApiFormsFormIdDisconnectSlackRouteImport } from './routes/api/forms/$formId/disconnect-slack'
import { Route as ApiFormsFormIdDisconnectDiscordRouteImport } from './routes/api/forms/$formId/disconnect-discord'
import { Route as ApiFormsFormIdAnalyticsRouteImport } from './routes/api/forms/$formId/analytics'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'
import { Route as ApiAdminSettingsClearOldSubmissionsRouteImport } from './routes/api/admin/settings/clear-old-submissions'
import { Route as ApiFormsFormIdSubmissionsSubmissionIdRouteImport } from './routes/api/forms/$formId/submissions/$submissionId'
import { Route as ApiFormsFormIdRecipientsRecipientIdRouteImport } from './routes/api/forms/$formId/recipients/$recipientId'
import { Route as ApiFormsFormIdRecipientsRecipientIdResendVerificationRouteImport } from './routes/api/forms/$formId/recipients/$recipientId/resend-verification'

const WelcomeToProRoute = WelcomeToProRouteImport.update({
  id: '/welcome-to-pro',
  path: '/welcome-to-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRecipientRoute = VerifyRecipientRouteImport.update({
  id: '/verify-recipient',
  path: '/verify-recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DocsIntegrationsRoute = DocsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormsRoute = DocsFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiVerifyRecipientRoute = ApiVerifyRecipientRouteImport.update({
  id: '/api/verify-recipient',
  path: '/api/verify-recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsRoute = ApiFormsRouteImport.update({
  id: '/api/forms',
  path: '/api/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysRoute = ApiApiKeysRouteImport.update({
  id: '/api/api-keys',
  path: '/api/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiUserSettingsRoute = ApiUserSettingsRouteImport.update({
  id: '/api/user/settings',
  path: '/api/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsFormIdRoute = ApiFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => ApiFormsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFormsRoute = ApiAdminFormsRouteImport.update({
  id: '/api/admin/forms',
  path: '/api/admin/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AppFormsIdSubmissionsRoute = AppFormsIdSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdSettingsRoute = AppFormsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdNotificationsRoute = AppFormsIdNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdIntegrationsRoute = AppFormsIdIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdAnalyticsRoute = AppFormsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackAuthorizeRoute =
  ApiIntegrationsSlackAuthorizeRouteImport.update({
    id: '/api/integrations/slack/authorize',
    path: '/api/integrations/slack/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsSpreadsheetsRoute =
  ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport.update({
    id: '/api/integrations/google-sheets/spreadsheets',
    path: '/api/integrations/google-sheets/spreadsheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsDisconnectRoute =
  ApiIntegrationsGoogleSheetsDisconnectRouteImport.update({
    id: '/api/integrations/google-sheets/disconnect',
    path: '/api/integrations/google-sheets/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsConfigureRoute =
  ApiIntegrationsGoogleSheetsConfigureRouteImport.update({
    id: '/api/integrations/google-sheets/configure',
    path: '/api/integrations/google-sheets/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsCallbackRoute =
  ApiIntegrationsGoogleSheetsCallbackRouteImport.update({
    id: '/api/integrations/google-sheets/callback',
    path: '/api/integrations/google-sheets/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsAuthorizeRoute =
  ApiIntegrationsGoogleSheetsAuthorizeRouteImport.update({
    id: '/api/integrations/google-sheets/authorize',
    path: '/api/integrations/google-sheets/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordAuthorizeRoute =
  ApiIntegrationsDiscordAuthorizeRouteImport.update({
    id: '/api/integrations/discord/authorize',
    path: '/api/integrations/discord/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFormsFormIdSubmissionsRoute =
  ApiFormsFormIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdRecipientsRoute =
  ApiFormsFormIdRecipientsRouteImport.update({
    id: '/recipients',
    path: '/recipients',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdExportRoute = ApiFormsFormIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiFormsFormIdRoute,
} as any)
const ApiFormsFormIdDisconnectSlackRoute =
  ApiFormsFormIdDisconnectSlackRouteImport.update({
    id: '/disconnect-slack',
    path: '/disconnect-slack',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdDisconnectDiscordRoute =
  ApiFormsFormIdDisconnectDiscordRouteImport.update({
    id: '/disconnect-discord',
    path: '/disconnect-discord',
    getParentRoute: () => ApiFormsFormIdRoute,
  } as any)
const ApiFormsFormIdAnalyticsRoute = ApiFormsFormIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ApiFormsFormIdRoute,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/api/admin/users/$userId',
  path: '/api/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsClearOldSubmissionsRoute =
  ApiAdminSettingsClearOldSubmissionsRouteImport.update({
    id: '/api/admin/settings/clear-old-submissions',
    path: '/api/admin/settings/clear-old-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFormsFormIdSubmissionsSubmissionIdRoute =
  ApiFormsFormIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ApiFormsFormIdSubmissionsRoute,
  } as any)
const ApiFormsFormIdRecipientsRecipientIdRoute =
  ApiFormsFormIdRecipientsRecipientIdRouteImport.update({
    id: '/$recipientId',
    path: '/$recipientId',
    getParentRoute: () => ApiFormsFormIdRecipientsRoute,
  } as any)
const ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute =
  ApiFormsFormIdRecipientsRecipientIdResendVerificationRouteImport.update({
    id: '/resend-verification',
    path: '/resend-verification',
    getParentRoute: () => ApiFormsFormIdRecipientsRecipientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-recipient': typeof VerifyRecipientRoute
  '/welcome-to-pro': typeof WelcomeToProRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/forms': typeof ApiAdminFormsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$formId': typeof ApiFormsFormIdRouteWithChildren
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/admin/users': typeof AdminUsersIndexRoute
  '/app/forms': typeof AppFormsIndexRoute
  '/api/admin/settings/clear-old-submissions': typeof ApiAdminSettingsClearOldSubmissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/forms/$formId/analytics': typeof ApiFormsFormIdAnalyticsRoute
  '/api/forms/$formId/disconnect-discord': typeof ApiFormsFormIdDisconnectDiscordRoute
  '/api/forms/$formId/disconnect-slack': typeof ApiFormsFormIdDisconnectSlackRoute
  '/api/forms/$formId/export': typeof ApiFormsFormIdExportRoute
  '/api/forms/$formId/recipients': typeof ApiFormsFormIdRecipientsRouteWithChildren
  '/api/forms/$formId/submissions': typeof ApiFormsFormIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof AppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof AppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/forms/$formId/recipients/$recipientId': typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
  '/api/forms/$formId/submissions/$submissionId': typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
  '/api/forms/$formId/recipients/$recipientId/resend-verification': typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-recipient': typeof VerifyRecipientRoute
  '/welcome-to-pro': typeof WelcomeToProRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/forms': typeof ApiAdminFormsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$formId': typeof ApiFormsFormIdRouteWithChildren
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/admin/users': typeof AdminUsersIndexRoute
  '/app/forms': typeof AppFormsIndexRoute
  '/api/admin/settings/clear-old-submissions': typeof ApiAdminSettingsClearOldSubmissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/forms/$formId/analytics': typeof ApiFormsFormIdAnalyticsRoute
  '/api/forms/$formId/disconnect-discord': typeof ApiFormsFormIdDisconnectDiscordRoute
  '/api/forms/$formId/disconnect-slack': typeof ApiFormsFormIdDisconnectSlackRoute
  '/api/forms/$formId/export': typeof ApiFormsFormIdExportRoute
  '/api/forms/$formId/recipients': typeof ApiFormsFormIdRecipientsRouteWithChildren
  '/api/forms/$formId/submissions': typeof ApiFormsFormIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof AppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof AppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/forms/$formId/recipients/$recipientId': typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
  '/api/forms/$formId/submissions/$submissionId': typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
  '/api/forms/$formId/recipients/$recipientId/resend-verification': typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-recipient': typeof VerifyRecipientRoute
  '/welcome-to-pro': typeof WelcomeToProRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/forms': typeof ApiAdminFormsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$formId': typeof ApiFormsFormIdRouteWithChildren
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/admin/users/': typeof AdminUsersIndexRoute
  '/app/forms/': typeof AppFormsIndexRoute
  '/api/admin/settings/clear-old-submissions': typeof ApiAdminSettingsClearOldSubmissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/forms/$formId/analytics': typeof ApiFormsFormIdAnalyticsRoute
  '/api/forms/$formId/disconnect-discord': typeof ApiFormsFormIdDisconnectDiscordRoute
  '/api/forms/$formId/disconnect-slack': typeof ApiFormsFormIdDisconnectSlackRoute
  '/api/forms/$formId/export': typeof ApiFormsFormIdExportRoute
  '/api/forms/$formId/recipients': typeof ApiFormsFormIdRecipientsRouteWithChildren
  '/api/forms/$formId/submissions': typeof ApiFormsFormIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof AppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof AppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/forms/$formId/recipients/$recipientId': typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
  '/api/forms/$formId/submissions/$submissionId': typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
  '/api/forms/$formId/recipients/$recipientId/resend-verification': typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/admin/forms'
    | '/admin/settings'
    | '/admin/submissions'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/forms'
    | '/api/subscription'
    | '/api/verify-recipient'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/admin/'
    | '/docs/'
    | '/admin/users/$userId'
    | '/api/admin/forms'
    | '/api/admin/stats'
    | '/api/admin/submissions'
    | '/api/auth/$'
    | '/api/forms/$formId'
    | '/api/user/settings'
    | '/app/forms/$id'
    | '/admin/users'
    | '/app/forms'
    | '/api/admin/settings/clear-old-submissions'
    | '/api/admin/users/$userId'
    | '/api/forms/$formId/analytics'
    | '/api/forms/$formId/disconnect-discord'
    | '/api/forms/$formId/disconnect-slack'
    | '/api/forms/$formId/export'
    | '/api/forms/$formId/recipients'
    | '/api/forms/$formId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/forms/$formId/recipients/$recipientId'
    | '/api/forms/$formId/submissions/$submissionId'
    | '/api/forms/$formId/recipients/$recipientId/resend-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/admin/forms'
    | '/admin/settings'
    | '/admin/submissions'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/forms'
    | '/api/subscription'
    | '/api/verify-recipient'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/admin'
    | '/docs'
    | '/admin/users/$userId'
    | '/api/admin/forms'
    | '/api/admin/stats'
    | '/api/admin/submissions'
    | '/api/auth/$'
    | '/api/forms/$formId'
    | '/api/user/settings'
    | '/app/forms/$id'
    | '/admin/users'
    | '/app/forms'
    | '/api/admin/settings/clear-old-submissions'
    | '/api/admin/users/$userId'
    | '/api/forms/$formId/analytics'
    | '/api/forms/$formId/disconnect-discord'
    | '/api/forms/$formId/disconnect-slack'
    | '/api/forms/$formId/export'
    | '/api/forms/$formId/recipients'
    | '/api/forms/$formId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/forms/$formId/recipients/$recipientId'
    | '/api/forms/$formId/submissions/$submissionId'
    | '/api/forms/$formId/recipients/$recipientId/resend-verification'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/admin/forms'
    | '/admin/settings'
    | '/admin/submissions'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/forms'
    | '/api/subscription'
    | '/api/verify-recipient'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/admin/'
    | '/docs/'
    | '/admin/users/$userId'
    | '/api/admin/forms'
    | '/api/admin/stats'
    | '/api/admin/submissions'
    | '/api/auth/$'
    | '/api/forms/$formId'
    | '/api/user/settings'
    | '/app/forms/$id'
    | '/admin/users/'
    | '/app/forms/'
    | '/api/admin/settings/clear-old-submissions'
    | '/api/admin/users/$userId'
    | '/api/forms/$formId/analytics'
    | '/api/forms/$formId/disconnect-discord'
    | '/api/forms/$formId/disconnect-slack'
    | '/api/forms/$formId/export'
    | '/api/forms/$formId/recipients'
    | '/api/forms/$formId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/forms/$formId/recipients/$recipientId'
    | '/api/forms/$formId/submissions/$submissionId'
    | '/api/forms/$formId/recipients/$recipientId/resend-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyRecipientRoute: typeof VerifyRecipientRoute
  WelcomeToProRoute: typeof WelcomeToProRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiApiKeysRoute: typeof ApiApiKeysRoute
  ApiFormsRoute: typeof ApiFormsRouteWithChildren
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiVerifyRecipientRoute: typeof ApiVerifyRecipientRoute
  ApiAdminFormsRoute: typeof ApiAdminFormsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserSettingsRoute: typeof ApiUserSettingsRoute
  ApiAdminSettingsClearOldSubmissionsRoute: typeof ApiAdminSettingsClearOldSubmissionsRoute
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
  ApiIntegrationsDiscordAuthorizeRoute: typeof ApiIntegrationsDiscordAuthorizeRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsGoogleSheetsAuthorizeRoute: typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  ApiIntegrationsGoogleSheetsCallbackRoute: typeof ApiIntegrationsGoogleSheetsCallbackRoute
  ApiIntegrationsGoogleSheetsConfigureRoute: typeof ApiIntegrationsGoogleSheetsConfigureRoute
  ApiIntegrationsGoogleSheetsDisconnectRoute: typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  ApiIntegrationsGoogleSheetsSpreadsheetsRoute: typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  ApiIntegrationsSlackAuthorizeRoute: typeof ApiIntegrationsSlackAuthorizeRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-to-pro': {
      id: '/welcome-to-pro'
      path: '/welcome-to-pro'
      fullPath: '/welcome-to-pro'
      preLoaderRoute: typeof WelcomeToProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-recipient': {
      id: '/verify-recipient'
      path: '/verify-recipient'
      fullPath: '/verify-recipient'
      preLoaderRoute: typeof VerifyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/integrations': {
      id: '/docs/integrations'
      path: '/integrations'
      fullPath: '/docs/integrations'
      preLoaderRoute: typeof DocsIntegrationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/forms': {
      id: '/docs/forms'
      path: '/forms'
      fullPath: '/docs/forms'
      preLoaderRoute: typeof DocsFormsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/verify-recipient': {
      id: '/api/verify-recipient'
      path: '/api/verify-recipient'
      fullPath: '/api/verify-recipient'
      preLoaderRoute: typeof ApiVerifyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms': {
      id: '/api/forms'
      path: '/api/forms'
      fullPath: '/api/forms'
      preLoaderRoute: typeof ApiFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys': {
      id: '/api/api-keys'
      path: '/api/api-keys'
      fullPath: '/api/api-keys'
      preLoaderRoute: typeof ApiApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/forms/': {
      id: '/app/forms/'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/forms/$id': {
      id: '/app/forms/$id'
      path: '/forms/$id'
      fullPath: '/app/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/user/settings': {
      id: '/api/user/settings'
      path: '/api/user/settings'
      fullPath: '/api/user/settings'
      preLoaderRoute: typeof ApiUserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$formId': {
      id: '/api/forms/$formId'
      path: '/$formId'
      fullPath: '/api/forms/$formId'
      preLoaderRoute: typeof ApiFormsFormIdRouteImport
      parentRoute: typeof ApiFormsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/forms': {
      id: '/api/admin/forms'
      path: '/api/admin/forms'
      fullPath: '/api/admin/forms'
      preLoaderRoute: typeof ApiAdminFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/forms/$id/submissions': {
      id: '/app/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/app/forms/$id/submissions'
      preLoaderRoute: typeof AppFormsIdSubmissionsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/settings': {
      id: '/app/forms/$id/settings'
      path: '/settings'
      fullPath: '/app/forms/$id/settings'
      preLoaderRoute: typeof AppFormsIdSettingsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/notifications': {
      id: '/app/forms/$id/notifications'
      path: '/notifications'
      fullPath: '/app/forms/$id/notifications'
      preLoaderRoute: typeof AppFormsIdNotificationsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/integrations': {
      id: '/app/forms/$id/integrations'
      path: '/integrations'
      fullPath: '/app/forms/$id/integrations'
      preLoaderRoute: typeof AppFormsIdIntegrationsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/analytics': {
      id: '/app/forms/$id/analytics'
      path: '/analytics'
      fullPath: '/app/forms/$id/analytics'
      preLoaderRoute: typeof AppFormsIdAnalyticsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/authorize': {
      id: '/api/integrations/slack/authorize'
      path: '/api/integrations/slack/authorize'
      fullPath: '/api/integrations/slack/authorize'
      preLoaderRoute: typeof ApiIntegrationsSlackAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/spreadsheets': {
      id: '/api/integrations/google-sheets/spreadsheets'
      path: '/api/integrations/google-sheets/spreadsheets'
      fullPath: '/api/integrations/google-sheets/spreadsheets'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/disconnect': {
      id: '/api/integrations/google-sheets/disconnect'
      path: '/api/integrations/google-sheets/disconnect'
      fullPath: '/api/integrations/google-sheets/disconnect'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/configure': {
      id: '/api/integrations/google-sheets/configure'
      path: '/api/integrations/google-sheets/configure'
      fullPath: '/api/integrations/google-sheets/configure'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/callback': {
      id: '/api/integrations/google-sheets/callback'
      path: '/api/integrations/google-sheets/callback'
      fullPath: '/api/integrations/google-sheets/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/authorize': {
      id: '/api/integrations/google-sheets/authorize'
      path: '/api/integrations/google-sheets/authorize'
      fullPath: '/api/integrations/google-sheets/authorize'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/authorize': {
      id: '/api/integrations/discord/authorize'
      path: '/api/integrations/discord/authorize'
      fullPath: '/api/integrations/discord/authorize'
      preLoaderRoute: typeof ApiIntegrationsDiscordAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$formId/submissions': {
      id: '/api/forms/$formId/submissions'
      path: '/submissions'
      fullPath: '/api/forms/$formId/submissions'
      preLoaderRoute: typeof ApiFormsFormIdSubmissionsRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/recipients': {
      id: '/api/forms/$formId/recipients'
      path: '/recipients'
      fullPath: '/api/forms/$formId/recipients'
      preLoaderRoute: typeof ApiFormsFormIdRecipientsRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/export': {
      id: '/api/forms/$formId/export'
      path: '/export'
      fullPath: '/api/forms/$formId/export'
      preLoaderRoute: typeof ApiFormsFormIdExportRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/disconnect-slack': {
      id: '/api/forms/$formId/disconnect-slack'
      path: '/disconnect-slack'
      fullPath: '/api/forms/$formId/disconnect-slack'
      preLoaderRoute: typeof ApiFormsFormIdDisconnectSlackRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/disconnect-discord': {
      id: '/api/forms/$formId/disconnect-discord'
      path: '/disconnect-discord'
      fullPath: '/api/forms/$formId/disconnect-discord'
      preLoaderRoute: typeof ApiFormsFormIdDisconnectDiscordRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/forms/$formId/analytics': {
      id: '/api/forms/$formId/analytics'
      path: '/analytics'
      fullPath: '/api/forms/$formId/analytics'
      preLoaderRoute: typeof ApiFormsFormIdAnalyticsRouteImport
      parentRoute: typeof ApiFormsFormIdRoute
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/api/admin/users/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings/clear-old-submissions': {
      id: '/api/admin/settings/clear-old-submissions'
      path: '/api/admin/settings/clear-old-submissions'
      fullPath: '/api/admin/settings/clear-old-submissions'
      preLoaderRoute: typeof ApiAdminSettingsClearOldSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$formId/submissions/$submissionId': {
      id: '/api/forms/$formId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/api/forms/$formId/submissions/$submissionId'
      preLoaderRoute: typeof ApiFormsFormIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ApiFormsFormIdSubmissionsRoute
    }
    '/api/forms/$formId/recipients/$recipientId': {
      id: '/api/forms/$formId/recipients/$recipientId'
      path: '/$recipientId'
      fullPath: '/api/forms/$formId/recipients/$recipientId'
      preLoaderRoute: typeof ApiFormsFormIdRecipientsRecipientIdRouteImport
      parentRoute: typeof ApiFormsFormIdRecipientsRoute
    }
    '/api/forms/$formId/recipients/$recipientId/resend-verification': {
      id: '/api/forms/$formId/recipients/$recipientId/resend-verification'
      path: '/resend-verification'
      fullPath: '/api/forms/$formId/recipients/$recipientId/resend-verification'
      preLoaderRoute: typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRouteImport
      parentRoute: typeof ApiFormsFormIdRecipientsRecipientIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFormsRoute: typeof AdminFormsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFormsRoute: AdminFormsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppFormsIdRouteChildren {
  AppFormsIdAnalyticsRoute: typeof AppFormsIdAnalyticsRoute
  AppFormsIdIntegrationsRoute: typeof AppFormsIdIntegrationsRoute
  AppFormsIdNotificationsRoute: typeof AppFormsIdNotificationsRoute
  AppFormsIdSettingsRoute: typeof AppFormsIdSettingsRoute
  AppFormsIdSubmissionsRoute: typeof AppFormsIdSubmissionsRoute
}

const AppFormsIdRouteChildren: AppFormsIdRouteChildren = {
  AppFormsIdAnalyticsRoute: AppFormsIdAnalyticsRoute,
  AppFormsIdIntegrationsRoute: AppFormsIdIntegrationsRoute,
  AppFormsIdNotificationsRoute: AppFormsIdNotificationsRoute,
  AppFormsIdSettingsRoute: AppFormsIdSettingsRoute,
  AppFormsIdSubmissionsRoute: AppFormsIdSubmissionsRoute,
}

const AppFormsIdRouteWithChildren = AppFormsIdRoute._addFileChildren(
  AppFormsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppFormsIdRoute: typeof AppFormsIdRouteWithChildren
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppFormsIdRoute: AppFormsIdRouteWithChildren,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsFormsRoute: typeof DocsFormsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIntegrationsRoute: typeof DocsIntegrationsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsFormsRoute: DocsFormsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIntegrationsRoute: DocsIntegrationsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiFormsFormIdRecipientsRecipientIdRouteChildren {
  ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute: typeof ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute
}

const ApiFormsFormIdRecipientsRecipientIdRouteChildren: ApiFormsFormIdRecipientsRecipientIdRouteChildren =
  {
    ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute:
      ApiFormsFormIdRecipientsRecipientIdResendVerificationRoute,
  }

const ApiFormsFormIdRecipientsRecipientIdRouteWithChildren =
  ApiFormsFormIdRecipientsRecipientIdRoute._addFileChildren(
    ApiFormsFormIdRecipientsRecipientIdRouteChildren,
  )

interface ApiFormsFormIdRecipientsRouteChildren {
  ApiFormsFormIdRecipientsRecipientIdRoute: typeof ApiFormsFormIdRecipientsRecipientIdRouteWithChildren
}

const ApiFormsFormIdRecipientsRouteChildren: ApiFormsFormIdRecipientsRouteChildren =
  {
    ApiFormsFormIdRecipientsRecipientIdRoute:
      ApiFormsFormIdRecipientsRecipientIdRouteWithChildren,
  }

const ApiFormsFormIdRecipientsRouteWithChildren =
  ApiFormsFormIdRecipientsRoute._addFileChildren(
    ApiFormsFormIdRecipientsRouteChildren,
  )

interface ApiFormsFormIdSubmissionsRouteChildren {
  ApiFormsFormIdSubmissionsSubmissionIdRoute: typeof ApiFormsFormIdSubmissionsSubmissionIdRoute
}

const ApiFormsFormIdSubmissionsRouteChildren: ApiFormsFormIdSubmissionsRouteChildren =
  {
    ApiFormsFormIdSubmissionsSubmissionIdRoute:
      ApiFormsFormIdSubmissionsSubmissionIdRoute,
  }

const ApiFormsFormIdSubmissionsRouteWithChildren =
  ApiFormsFormIdSubmissionsRoute._addFileChildren(
    ApiFormsFormIdSubmissionsRouteChildren,
  )

interface ApiFormsFormIdRouteChildren {
  ApiFormsFormIdAnalyticsRoute: typeof ApiFormsFormIdAnalyticsRoute
  ApiFormsFormIdDisconnectDiscordRoute: typeof ApiFormsFormIdDisconnectDiscordRoute
  ApiFormsFormIdDisconnectSlackRoute: typeof ApiFormsFormIdDisconnectSlackRoute
  ApiFormsFormIdExportRoute: typeof ApiFormsFormIdExportRoute
  ApiFormsFormIdRecipientsRoute: typeof ApiFormsFormIdRecipientsRouteWithChildren
  ApiFormsFormIdSubmissionsRoute: typeof ApiFormsFormIdSubmissionsRouteWithChildren
}

const ApiFormsFormIdRouteChildren: ApiFormsFormIdRouteChildren = {
  ApiFormsFormIdAnalyticsRoute: ApiFormsFormIdAnalyticsRoute,
  ApiFormsFormIdDisconnectDiscordRoute: ApiFormsFormIdDisconnectDiscordRoute,
  ApiFormsFormIdDisconnectSlackRoute: ApiFormsFormIdDisconnectSlackRoute,
  ApiFormsFormIdExportRoute: ApiFormsFormIdExportRoute,
  ApiFormsFormIdRecipientsRoute: ApiFormsFormIdRecipientsRouteWithChildren,
  ApiFormsFormIdSubmissionsRoute: ApiFormsFormIdSubmissionsRouteWithChildren,
}

const ApiFormsFormIdRouteWithChildren = ApiFormsFormIdRoute._addFileChildren(
  ApiFormsFormIdRouteChildren,
)

interface ApiFormsRouteChildren {
  ApiFormsFormIdRoute: typeof ApiFormsFormIdRouteWithChildren
}

const ApiFormsRouteChildren: ApiFormsRouteChildren = {
  ApiFormsFormIdRoute: ApiFormsFormIdRouteWithChildren,
}

const ApiFormsRouteWithChildren = ApiFormsRoute._addFileChildren(
  ApiFormsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyRecipientRoute: VerifyRecipientRoute,
  WelcomeToProRoute: WelcomeToProRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiApiKeysRoute: ApiApiKeysRoute,
  ApiFormsRoute: ApiFormsRouteWithChildren,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiVerifyRecipientRoute: ApiVerifyRecipientRoute,
  ApiAdminFormsRoute: ApiAdminFormsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserSettingsRoute: ApiUserSettingsRoute,
  ApiAdminSettingsClearOldSubmissionsRoute:
    ApiAdminSettingsClearOldSubmissionsRoute,
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
  ApiIntegrationsDiscordAuthorizeRoute: ApiIntegrationsDiscordAuthorizeRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsGoogleSheetsAuthorizeRoute:
    ApiIntegrationsGoogleSheetsAuthorizeRoute,
  ApiIntegrationsGoogleSheetsCallbackRoute:
    ApiIntegrationsGoogleSheetsCallbackRoute,
  ApiIntegrationsGoogleSheetsConfigureRoute:
    ApiIntegrationsGoogleSheetsConfigureRoute,
  ApiIntegrationsGoogleSheetsDisconnectRoute:
    ApiIntegrationsGoogleSheetsDisconnectRoute,
  ApiIntegrationsGoogleSheetsSpreadsheetsRoute:
    ApiIntegrationsGoogleSheetsSpreadsheetsRoute,
  ApiIntegrationsSlackAuthorizeRoute: ApiIntegrationsSlackAuthorizeRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
